[BUGFIX] refactor inheritance process
pixelant/pxa_product_manager pull request #305
Opened 2021-09-14 09:33 UTC by pixelmatseriks

# New Pull Request checklist

## PR Type

What kind of change does this PR introduce?

- [ ] [FEATURE] - A new feature
- [x] [BUGFIX] - A bug fix
- [ ] [TASK] - Any task, which is not a **new feature** or **bugfix**
- [ ] [TEST] - Adding missing tests
- [ ] [DOC] - Documentation only changes
- [ ] [WIP] - Work in progress tag, should not be present when creating pull requests

## Breaking change

Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Description

2021-09-14 14:32 UTC, mabolek requested changes

2021-09-14 14:32 UTC, mabolek commented on Classes/Utility/DataInheritanceUtility.php
> +            )[$identifierField];
What do you do when BackendUtility::getRecord() returns null?

2021-09-14 14:32 UTC, mabolek commented on Classes/Utility/DataInheritanceUtility.php
>  {
Some really great stuff in this class!!!

2021-09-14 14:32 UTC, mabolek commented on Configuration/Services.yaml
> +        before: ''
Isn't it possible to just skip the `before`?

2021-09-14 14:32 UTC, mabolek commented on ext_localconf.php
> +    //    \Pixelant\PxaProductManager\Hook\FlexFormDataStructureHook::class;
```suggestion
```

2021-09-15 07:38 UTC, pixelmatseriks commented on Classes/Command/FixDuplicateAttributeValuesCommand.php
> +    protected function fetchAttributeValuesByProductAndAttribute(int $product, int $attribute): array
Hmm, I'm not sure, this function returns all attributevalues by product and attribute, hopefully it won't be needed in future.

2021-09-15 07:41 UTC, pixelmatseriks commented on Classes/Command/FixDuplicateAttributeValuesCommand.php
> +    protected function fetchAttributeValueById(int $id): array
Not same table, attributevalue vs attribute.

2021-09-15 07:42 UTC, pixelmatseriks commented on Classes/Command/FixDuplicateAttributeValuesCommand.php
> +    protected function removeDuplicateAttributeValuesAndRii(array $attributeValues): void
old code, removed now, but meant tx_pxaproductmanager_relation_inheritance_index

2021-09-15 09:28 UTC, merged