[TASK] update TCA configuration
pixelant/pxa_product_manager pull request #382
Opened 2022-05-19 05:59 UTC by pixelmatseriks

# New Pull Request checklist

## PR Type

What kind of change does this PR introduce?

Alter TCA configuration to avoid loading attributes and products for attributevalues, to increase performance when editing producs in TYPO3 BE. Small code update to adapt to the TCA changes. 

- [ ] [FEATURE] - A new feature
- [ ] [BUGFIX] - A bug fix
- [x] [TASK] - Any task, which is not a **new feature** or **bugfix**
- [ ] [TEST] - Adding missing tests
- [ ] [DOC] - Documentation only changes
- [ ] [WIP] - Work in progress tag, should not be present when creating pull requests

## Breaking change

Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Description

2022-05-19 06:44 UTC, mabolek requested changes

2022-05-19 06:44 UTC, mabolek commented on Configuration/TCA/tx_pxaproductmanager_domain_model_attributevalue.php
> +                'type' => 'passthrough',
I think this configuration is useful for interest-based imports as well as reference index. What do you think? The interest extension needs to know if something is a relation, and I think it's not so good to not specify it in the data schema.

2022-05-19 06:44 UTC, mabolek commented on Configuration/TCA/tx_pxaproductmanager_domain_model_attributevalue.php
> +                'type' => 'passthrough',
I think this configuration is useful for interest-based imports as well as reference index. What do you think? The interest extension needs to know if something is a relation, and I think it's not so good to not specify it in the data schema.

2022-05-20 06:14 UTC, mabolek approved these changes

2022-05-23 09:00 UTC, MattiasNilsson approved these changes
Nice 👍

2022-05-23 10:28 UTC, merged